# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SPAIRL
email: gjones13@leomail.tamuc.edu
# description: > # this means to ignore newlines until "baseurl:"
# Website to display research from SPAIRL - .  This research group is under the
# direction of Dr. Srujan Kotikela and focuses on solutions to decentralized identity.
# baseurl: "localhost"
url: "http://localhost:4000"

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

include:
  - .htaccess
  - '_pages'

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

